name: CustomPlayerAdvancements
version: 1.0.0
main: afx.customplayeradvancements.CustomPlayerAdvancements
api-version: '26.2'

depend:
  - ProtocolLib

softdepend:
  - PlaceholderAPI

commands:
  ancustomizer:
    description: CustomPlayerAdvancements commands
    usage: /ancustomizer <reload>
    aliases:
      - advancementnamecustomizer
      - anc
      - advancements

permissions:
  ancustomizer.reload:
    description: Allows reloading the plugin
    default: op
