name: CustomAdvancementMessages
version: 1.0.1
main: afx.customadvancementmessages.CustomAdvancementMessages
api-version: '1.20'
author: AFXPlugins
description: >
  Fully customizable advancement messages.

depend:
  - packetevents
  - PlaceholderAPI

commands:
  advancements:
    description: CustomAdvancementMessages commands
    usage: /advancements <reload|update|preview>
    aliases: [customadvancementmessages]
    permission: customadvancementmessages.admin
    permission-message: You do not have permission to use this command.

permissions:
  customadvancementmessages.admin:
    description: Allows use of all CustomAdvancementMessages commands.
    default: op
  customadvancementmessages.updatenotify:
    description: Receive a message on join when a new plugin update is available.
    default: op